### ISSUE TITLE
Make the allowed groups configurable - currently hard-coded to 'Administrators'

### ISSUE THREAD

**Issue by LottePitcher** [LottePitcher/umbraco-admin-only-property#1]
Add a new configuration option to the data type so that the groups that are allowed to see the property is configurable. 

Perhaps as a check button list? When creating the data type 'Administrators' should be enabled by default. Would we need to validate that at least one group has been checked?

**Comment by bjarnef** [comment]
Could it simple use the existing user group infinite editor?
https://github.com/umbraco/Umbraco-CMS/tree/v11/contrib/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/usergrouppicker

This is already used on a user to select user groups:
https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.UI.Client/src/views/users/user.controller.js#L256-L273

**Comment by leekelleher** [comment]
@bjarnef Is the User Group picker available as a property-editor, or prevalue-editor? _(I looked but couldn't find it)_

**Comment by LottePitcher** [comment]
Hey @bjarnef - I'm up for whatever implementation people think makes sense!

**Comment by bjarnef** [comment]
@leekelleher not as a prevalue editor OOTB, which I probably what we want here in the datatype configuration.
https://github.com/umbraco/Umbraco-CMS/tree/v11/contrib/src/Umbraco.Web.UI.Client/src/views/prevalueeditors

But it should be simple enough to create a custom prevalue editor, use the infinite user group picker here and initial the datatype with Administrators as default selected user group.
