### ISSUE TITLE
Feature request: Visualize that a property is "for your admin eyes only"

### ISSUE THREAD

**Issue by greystate** [LottePitcher/umbraco-admin-only-property#12]
It would be very nice if a property that have been wrapped like this could provide some kind of clue for you that it has indeed been made _Admin-only_. I was looking for a way to do it just by adding a custom CSS file to the backoffice, but couldn't find any hooks to grab on to... (I have no idea about the inner workings of this, so don't know if it's at all feasible).

**Comment by LottePitcher** [comment]
Thanks @greystate - this _would_ be a good idea! Shall investigate!

**Comment by LottePitcher** [comment]
Thanks for the suggestion @greystate.  So this package _just_ interrupts the loading of content to remove the properties that are restricted when the user doesn't have the appropriate permissions. So the package itself isn't rendering any html/css.

However, during this `SendingContentNotification` handler, we can add a prefix or a suffix to the label or the description of the property before it is displayed. For example, we could display the unlocked padlock emoji to the label:

![image](https://user-images.githubusercontent.com/4716542/203417928-0e7dea8d-a395-4bff-8f07-c0accd473315.png)

Do you think this is worth implementing? If so I think I would add a new configuration option to the datatype so the implementer can choose to switch this on if they want.  At the hackathon last week we played around with a few different emojis, both before and after, and decided the unlocked padlock before the label looked the best.

**Comment by greystate** [comment]
That's totally worth it IMHO. It's really just to get that _piece of mind_ thing that tells you it's an admin-only property.

Looks great 👍

**Comment by LottePitcher** [comment]
Fixed by https://github.com/LottePitcher/umbraco-admin-only-property/commit/4a3f4fc51c6506e688a623f0c5de460a732a030f and now released in [v1.1.0](https://github.com/LottePitcher/umbraco-admin-only-property/releases/tag/1.1.0)

Now you have a new option to 'show indicator' to make this happen. Thanks for the suggestion @greystate
