### ISSUE TITLE
Installed package hides tabs on content nodes

### ISSUE THREAD

**Issue by robertjf** [LottePitcher/umbraco-admin-only-property#14]
We noticed after installing the package and adding an experimental property (wrapping the text editor) that tabs have started disappearing from the content nodes.

Without the package installed:

![image](https://user-images.githubusercontent.com/818101/204702322-a091a240-3408-4910-9c70-b8aebf7ae5cb.png)

With the package installed:
![Screenshot 2022-11-30 at 2 41 47 pm](https://user-images.githubusercontent.com/818101/204702380-410ac61a-fffd-48a7-8d62-e10a458fb7be.png)

In some cases, the contents from the hidden tabs are not visible (but not all tabs are gone); while in others all tabs are gone but the content is displayed.

Also, tabs inherited by composition are still there.

Umbraco version: *10.3.2*
DotNet version: *net7.0*

**Comment by LottePitcher** [comment]
Hi Robert,

Sorry to hear that your first experience with the package is somewhat problematic.

The 'removal' of tabs should only happen if there are no properties on the tab after any 'restricted' ones have been removed, as you can see on this bit of code:

https://github.com/LottePitcher/umbraco-admin-only-property/blob/a22f9711541e20af27cb1f73ee42b82042948589/src/AdminOnlyProperty/AdminOnlyPropertySendingContentNotificationHandler.cs#L60-L63

I have this working on a couple of sites and have not experienced the disappearing of tabs that you describe.
We have a 'admin only' textarea in a composition, and that works as expected.

You used the word 'inheritance' in your post, which makes me realise I've not tested anything with _actual_ inheritance, but as I say I have it working in a composition ok.

If there is an easy way for you to share with me your configuration (perhaps uSync config files?) I could try and see what's happening here.

Lotte

**Comment by LottePitcher** [comment]
Thanks @GijsD-iD for the feedback. I've not tested with groups (confession, haven't used them for ages), but I'll see if I can replicate what you report as yes it sounds a sensible thing to support if feasible

**Comment by martinbrud** [comment]
> 

I have the exact same issue: Tabs where all properties are under group(s). 

https://i.imgur.com/NDuH19n.png

Umbraco version: 11.2.0
DotNet version: net7.0

**Comment by LottePitcher** [comment]
Thanks @martinbrud for your feedback.

I have replicated this issue and it has been fixed in commit bc965b1.

The fix will be coming in the next release, which I should be able to get done next week. I'll update this issue as soon as it is.

**Comment by LottePitcher** [comment]
version 1.1.2 has been released which fixes this
