### ISSUE TITLE
BlockList Not Rendering

### ISSUE THREAD

**Issue by TRexStark** [LottePitcher/umbraco-admin-only-property#19]
Hi @LottePitcher

I found another issue - not sure if it's my instance of umbraco but when I use a BlockList as DataType, it doesn't render in the Front-End. The datatype is recognised as a BlockList item but I can get the content from it.

Just a note, I don't use the default Umbraco way of rendering BlockLists, I get the DataType, then I check if there are any items to loop and get them.

Please let me know if you need more details and code sample to show you.

Thanks

**Comment by LottePitcher** [comment]
Hey @TRexStark so sorry for not getting back to you before now! I've blame things getting lost as the calendar year switched over...

I haven't tried the package with the standard blocklist. So I'll give that a go and see what happens.  Thanks for the feedback

**Comment by LottePitcher** [comment]
Hi @TRexStark,

I have added a block list property to the test site that is now in the repo, and yes it does look like the blocklist property has no contents when the property is rendered in the front-end.

I don't quite know how to proceed with investigating this... but for now I'm going to list out steps on how to replicate this using the test site in case anyone else has some bright ideas!

How to replicate:

- Clone the repo and run/view the AdminOnlyProperty.TestSite
- Log in as the administrator - [see contributing guidelines for login details](https://github.com/LottePitcher/umbraco-admin-only-property/blob/develop/.github/CONTRIBUTING.md)
- Click on the 'Restricted and Other Properties' content node - you'll see that there are two block list properties: one in the first group for All Users, and one in the second group for Admins Only.  Both block list properties do have content
- Now view this content node in the front-end - you should see that the 'admin only' block list property is not showing any contents.
