### ISSUE TITLE
Add Umbraco 13 support?

### ISSUE THREAD

**Issue by erikjanwestendorp** [LottePitcher/umbraco-admin-only-property#32]
### Feature summary

We are upgrading one of our client projects to Umbraco 13. We use this great package to hide some properties for users, but it seems this package is not ready for Umbraco 13 yet.

**Comment by erikjanwestendorp** [comment]
@LottePitcher Sorry, I think I was a bit too quick. 😅 I see that a [PR ](https://github.com/LottePitcher/umbraco-admin-only-property/pull/31)has already been created. I will wait patiently until it is merged.

**Comment by LottePitcher** [comment]
Hey @erikjanwestendorp, yes thanks to that pull request with a fix for v13, I have been able to get a new release out. I've tested v1.1.4 on an upgrade and a new v13 install so 🤞 you can finish upgrading your client's project now (or more likely after Christmas!)

https://www.nuget.org/packages/Our.Umbraco.Community.AdminOnlyProperty/1.1.4

I'd love to hear confirmation that this is all ok as it's the first time I've implemented multi-targeting. So I'll leave this issue open and hope to see it closed when you've had a chance to try again

**Comment by erikjanwestendorp** [comment]
@LottePitcher Thank you very much for the new version! 😄 I can confirm that this works as expected! Merry Christmas and a Happy New Year! 🎄🎅

**Comment by LottePitcher** [comment]
@erikjanwestendorp Hurray, thanks for confirming so soon. Happy Christmas and New Year to you too!
